# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Sets up JDK
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
         
       # Make Maven clean and package
      - name: Maven Package
        run: mvn -B clean package -DskipTests
        
      # Add test coverage
      - name: Test Coverage
        uses: codecov/codecov-action@v1.4.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: target\surefire-reports
